apiVersion: faspix.com/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: operator-k8s
    app.kubernetes.io/managed-by: kustomize
  name: project-sample
spec:
  owner: "dev-team-1" # Team responsible for this project
  environments:
    - name: prod # Production environment
      networkpolicies:
        denyall: true # Deny all inbound traffic by default
        allowdns: false # Disable DNS access
        allowegressinternet: false # Disable internet egress
        allowingressfromsamenamespace: true # Allow ingress within the same namespace
        allowingressfromothernamespaces: true # Allow ingress from other namespaces
      finalizers:
        - kubernetes # Ensure cleanup on deletion
      serviceaccounts:
        - deploy # Service account for CI/CD
        - monitoring # Service account for monitoring
      podsecurity:
        type: audit # Pod security policy type
        level: baseline # Security level
        version: latest # Use the latest version
      resources:
        quota: # Resource quotas for the namespace
          pods: 20 # integer
          configmaps: 20 # integer
          secrets: 20 # integer
          storage: "100Gi"
          requests:
            cpu: "5"
            memory: "50Gi"
          limits:
            cpu: "8"
            memory: "80Gi"
        defaultlimitrange: # Default resource limits for pods
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
          max:
            cpu: "1"
            memory: "1Gi"
          min: 
            cpu: "100m"
            memory: "128Mi"
    - name: stage # Staging environment
      resources:
        defaultlimitrange:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "0.8"
            memory: "1Gi"
    - name: dev # Development environment
  rbac: # Role-based access control
    admingroup: "dev-team-1-admins" # Admin group with full access
    devgroup: "dev-team-1-devs" # Developer group with edit access
    viewergroup: "dev-team-1-viewers" # Viewer group with read-only access

