apiVersion: faspix.com/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: operator-k8s
    app.kubernetes.io/managed-by: kustomize
  name: project-sample
spec:
  owner: "dev-team-1"
  environments:
    - name: prod
      networkpolicies:
        denyall: true
        allowdns: false
        allowegressinternet: false
        allowingressfromsamenamespace: true
        allowingressfromothernamespaces: true
      finalizers:
        - kubernetes
      serviceaccounts:
        - acc1
        - acc2
      podsecurity:
        type: audit
        level: baseline
        version: latest
      resources:
        quota:
          pods: 20
          configmaps: 20
          secrets: 20
          storage: "100Gi"
          requests:
            cpu: "5"
            memory: "50Gi"
          limits:
            cpu: "8"
            memory: "80Gi"
        defaultlimitrange:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
          max:
            cpu: "1"
            memory: "1Gi"
          min: 
            cpu: "100m"
            memory: "128Mi"
    - name: stage
      resources:
        defaultlimitrange:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "0.8"
            memory: "1Gi"
    - name: dev
  rbac:
    admingroup: "dev-team-1-admins"
    devgroup: "dev-team-1-devs"
    viewergroup: "dev-team-1-viewers"
