apiVersion: faspix.com/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: operator-k8s
    app.kubernetes.io/managed-by: kustomize
  name: project-sample
spec:
  owner: "dev-team-1"
  environments:
    - name: prod
      resources:
        quota:
          requests:
            cpu: 5
            memory: 50Gi
            storage: 100Gi
          limits:
            pods: 20
            cpu: 8
            memory: 80Gi
        defaultLimitRange:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
          max:
            cpu: 1
            memory: 1Gi
          min: 
            cpu: 100m
            memory: 128Mi
    - name: stage
      resources:
        defaultLimitRange:
          requests:
            cpu: 0.5
            memory: 1Gi
          limits:
            cpu: 0.8
            memory: 1Gi
    - name: dev
  rbac:
    adminGroup: "dev-team-1-admins"
    devGroup: "dev-team-1-devs"
    viewerGroup: "dev-team-1-viewers"
