---
- name: Set common labels
  set_fact:
    common_labels:
      app.kubernetes.io/managed-by: projects-operator
      faspix.com/owner: "{{ owner }}"
      faspix.com/project: "{{ ansible_operator_meta.name }}"

- import_tasks: namespace.yml
- import_tasks: resource_quota.yml
- import_tasks: limitrange.yml
- import_tasks: rbac.yml
- import_tasks: networkpolicies.yml
- import_tasks: serviceaccounts.yml


