---
- name: Set common labels
  set_fact:
    common_labels:
      app.kubernetes.io/managed-by: projects-operator
      faspix.com/owner: "{{ owner }}"
      faspix.com/project: "{{ ansible_operator_meta.name }}"

- name: Create a namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels: >-
          {{
            common_labels | combine({
              'faspix.com/environment': item.name,
              'pod-security.kubernetes.io/' ~ (item.podsecurity.type | default(projects_operator_default_podSecurity_type, true)):
                (item.podsecurity.level | default(projects_operator_default_podSecurity_level, true)),
              'pod-security.kubernetes.io/' ~ (item.podsecurity.type | default(projects_operator_default_podSecurity_type, true)) ~ '-version':
                (item.podsecurity.version | default(projects_operator_default_podSecurity_version, true)),
            })
          }}
      finalizers: "{{ item.get('finalizers', [projects_operator_default_finalizer]) }}"
  loop: "{{ environments }}"

- name: Create a resource quota
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        name: resource-quota
        labels: "{{ common_labels | combine({'faspix.com/environment': item.name}) }}"
      spec:
        hard:
          pods: "{{ item.resources.quota.pods | default(projects_operator_default_quota_pods) }}"
          configmaps: "{{ item.resources.quota.configmaps | default(projects_operator_default_quota_configmaps) }}"
          secrets: "{{ item.resources.quota.secrets | default(projects_operator_default_quota_secrets) }}"
          limits.cpu: "{{ item.resources.quota.limits.cpu | default(projects_operator_default_quota_limit_cpu) }}"
          limits.memory: "{{ item.resources.quota.limits.memory | default(projects_operator_default_quota_limit_memory) }}"
          requests.cpu: "{{ item.resources.quota.requests.cpu | default(projects_operator_default_quota_request_cpu) }}"
          requests.memory: "{{ item.resources.quota.requests.memory | default(projects_operator_default_quota_request_memory) }}"
          requests.storage: "{{ item.resources.quota.requests.storage | default(projects_operator_default_quota_storage) }}"
  loop: "{{ environments }}"

- name: Create LimitRange
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: LimitRange
      metadata:
        name: default-limits
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels: "{{ common_labels | combine({'faspix.com/environment': item.name}) }}"
      spec:
        limits:
          - type: Container
            default:
              cpu: "{{ item.resources.defaultlimitrange.limits.cpu | default(projects_operator_default_limit_cpu) }}"
              memory: "{{ item.resources.defaultlimitrange.limits.memory | default(projects_operator_default_limit_memory) }}"
            defaultRequest:
              cpu: "{{ item.resources.defaultlimitrange.requests.cpu | default(projects_operator_default_request_cpu) }}"
              memory: "{{ item.resources.defaultlimitrange.requests.memory | default(projects_operator_default_request_memory) }}"
            max:
              cpu: "{{ item.resources.defaultlimitrange.max.cpu | default(projects_operator_default_max_cpu) }}"
              memory: "{{ item.resources.defaultlimitrange.max.memory | default(projects_operator_default_max_memory) }}"
            min:
              cpu: "{{ item.resources.defaultlimitrange.min.cpu | default(projects_operator_default_min_cpu) }}"
              memory: "{{ item.resources.defaultlimitrange.min.memory | default(projects_operator_default_min_memory) }}"
  loop: "{{ environments }}"

- name: Create RBAC - Admins
  kubernetes.core.k8s:
    state: present
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: admin-access
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels: "{{ common_labels | combine({'faspix.com/environment': item.name}) }}"
      subjects:
        - kind: Group
          name: "{{ rbac.admingroup }}"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: admin
        apiGroup: rbac.authorization.k8s.io
  loop: "{{ environments }}"

- name: Create RBAC - Developers
  kubernetes.core.k8s:
    state: present
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: edit-access
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels: "{{ common_labels | combine({'faspix.com/environment': item.name}) }}"
      subjects:
        - kind: Group
          name: "{{ rbac.devgroup }}"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: edit
        apiGroup: rbac.authorization.k8s.io
  loop: "{{ environments }}"

- name: Create RBAC - Viewers
  kubernetes.core.k8s:
    state: present
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: view-access
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels: "{{ common_labels | combine({'faspix.com/environment': item.name}) }}"
      subjects:
        - kind: Group
          name: "{{ rbac.viewergroup }}"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: view
        apiGroup: rbac.authorization.k8s.io
  loop: "{{ environments }}"

- name: Create default deny-all NetworkPolicy
  kubernetes.core.k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: deny-all
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels: "{{ common_labels | combine({'faspix.com/environment': item.name}) }}"
      spec:
        podSelector: {}
        policyTypes:
          - Ingress
          - Egress
  loop: "{{ environments }}"
  when: (item.networkpolicies.denyall | default(projects_operator_default_networkPolicies_denyAll))

- name: Allow DNS
  kubernetes.core.k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: allow-dns
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels: "{{ common_labels | combine({'faspix.com/environment': item.name}) }}"
      spec:
        podSelector: {}
        policyTypes:
          - Egress
        egress:
          - to:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: kube-system
            ports:
              - protocol: UDP
                port: 53
              - protocol: TCP
                port: 53
  loop: "{{ environments }}"
  when: (item.networkpolicies.allowdns | default(projects_operator_default_networkPolicies_allowDNS))

- name: Allow egress to internet
  kubernetes.core.k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: allow-egress-internet
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels: "{{ common_labels | combine({'faspix.com/environment': item.name}) }}"
      spec:
        podSelector: {}
        policyTypes:
          - Egress
        egress:
          - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
  loop: "{{ environments }}"
  when: (item.networkpolicies.allowegressinternet | default(projects_operator_default_networkPolicies_allowEgressInternet))

- name: Allow ingress from same namespace
  kubernetes.core.k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: allow-same-namespace
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels: "{{ common_labels | combine({'faspix.com/environment': item.name}) }}"
      spec:
        podSelector: {}
        policyTypes:
          - Ingress
        ingress:
          - from:
              - podSelector: {}
  loop: "{{ environments }}"
  when: (item.networkpolicies.allowingressfromsamenamespace | default(projects_operator_default_networkPolicies_allowIngressFromSameNamespace))

- name: Allow ingress from other namespaces
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-ingress-from-namespaces
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels: "{{ common_labels | combine({'faspix.com/environment': item.name}) }}"
      spec:
        podSelector: {}
        policyTypes: [Ingress]
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    faspix.com/project: "{{ ansible_operator_meta.name }}"
  loop: "{{ environments }}"
  when: (item.networkpolicies.allowingressfromothernamespaces | default(projects_operator_default_networkPolicies_allowIngressFromOtherNamespaces))

- name: Create ServiceAccounts
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ sa }}"
        namespace: "{{ ansible_operator_meta.name }}-{{ env.name }}"
        labels: "{{ common_labels | combine({'faspix.com/environment': env.name}) }}"
  loop: "{{ environments | subelements('serviceaccounts', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.name }} - {{ item.1 }}"
  vars:
    env: "{{ item.0 }}"
    sa: "{{ item.1 }}"
