---
- name: Create a namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels:
          app.kubernetes.io/managed-by: "projects-operator"
          faspix.project/owner: "{{ owner }}"
  loop: "{{ environments }}"

- name: Create a resource quota
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        name: resource-quota
        labels:
          app.kubernetes.io/managed-by: "projects-operator"
          faspix.project/owner: "{{ owner }}"
      spec:
        hard:
          limits.cpu: "{{ item.resources.limits.cpu | default(projects_operator_default_limit_cpu, true)}}"
          limits.memory: "{{ item.resources.limits.memory | default(projects_operator_default_limit_memory, true)}}"
          requests.cpu: "{{ item.resources.requests.cpu | default(projects_operator_default_request_cpu, true)}}"
          requests.memory: "{{ item.resources.requests.memory | default(projects_operator_default_request_memory, true)}}"
  loop: "{{ environments }}"

- name: Create LimitRange
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: LimitRange
      metadata:
        name: default-limits
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels:
          app.kubernetes.io/managed-by: "projects-operator"
          faspix.project/owner: "{{ owner }}"
      spec:
        limits:
          - type: Container
            default:
              cpu: "{{ item.resources.limits.cpu | default(projects_operator_default_limit_cpu, true)}}"
              memory: "{{ item.resources.limits.memory | default(projects_operator_default_limit_memory, true)}}"
            defaultRequest:
              cpu: "{{ item.resources.requests.cpu | default(projects_operator_default_request_cpu, true)}}"
              memory: "{{ item.resources.requests.memory | default(projects_operator_default_request_memory, true)}}"
  loop: "{{ environments }}"

- name: Create RBAC - Admins
  kubernetes.core.k8s:
    state: present
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: admin-access
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels:
          app.kubernetes.io/managed-by: "projects-operator"
          faspix.project/owner: "{{ owner }}"
      subjects:
        - kind: Group
          name: "{{ rbac.adminGroup }}"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: admin
        apiGroup: rbac.authorization.k8s.io
  loop: "{{ environments }}"

- name: Create RBAC - Developers
  kubernetes.core.k8s:
    state: present
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: edit-access
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels:
          app.kubernetes.io/managed-by: "projects-operator"
          faspix.project/owner: "{{ owner }}"
      subjects:
        - kind: Group
          name: "{{ rbac.devGroup }}"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: edit
        apiGroup: rbac.authorization.k8s.io
  loop: "{{ environments }}"

- name: Create RBAC - Viewers
  kubernetes.core.k8s:
    state: present
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: view-access
        namespace: "{{ ansible_operator_meta.name }}-{{ item.name }}"
        labels:
          app.kubernetes.io/managed-by: "projects-operator"
          faspix.project/owner: "{{ owner }}"
      subjects:
        - kind: Group
          name: "{{ rbac.viewerGroup }}"
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: view
        apiGroup: rbac.authorization.k8s.io
  loop: "{{ environments }}"


