---
- name: Create ServiceAccounts
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ sa }}"
        namespace: "{{ ansible_operator_meta.name }}-{{ env.name }}"
        labels: "{{ common_labels | combine({'faspix.com/environment': env.name}) }}"
  loop: "{{ environments | subelements('serviceaccounts', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.name }} - {{ item.1 }}"
  vars:
    env: "{{ item.0 }}"
    sa: "{{ item.1 }}"
