---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.faspix.com
spec:
  group: faspix.com
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Project is the Schema for the projects API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Project
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              owner:
                type: string
                description: Owner of the project
              environments:
                type: array
                description: List of environments to create in the project
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Environment name
                    podsecurity:
                      type: object
                      properties:
                        type:
                          type: string
                          description: Pod Security standard type (baseline, restricted, privileged)
                        level:
                          type: string
                        version:
                          type: string
                    resources:
                      type: object
                      properties:
                        quota:
                          type: object
                          properties:
                            pods:
                              type: integer
                            configmaps:
                              type: integer
                            secrets:
                              type: integer
                            storage:
                              type: string
                            limits:
                              type: object
                              properties:
                                cpu:
                                  type: string
                                memory:
                                  type: string
                            requests:
                              type: object
                              properties:
                                cpu:
                                  type: string
                                memory:
                                  type: string
                        defaultlimitrange:
                          type: object
                          properties:
                            limits:
                              type: object
                              properties:
                                cpu:
                                  type: string
                                memory:
                                  type: string
                            requests:
                              type: object
                              properties:
                                cpu:
                                  type: string
                                memory:
                                  type: string
                            max:
                              type: object
                              properties:
                                cpu:
                                  type: string
                                memory:
                                  type: string
                            min:
                              type: object
                              properties:
                                cpu:
                                  type: string
                                memory:
                                  type: string
                    networkpolicies:
                      type: object
                      properties:
                        denyall:
                          type: boolean
                        allowdns:
                          type: boolean
                        allowegressinternet:
                          type: boolean
                        allowingressfromothernamespaces:
                          type: boolean
                        allowingressfromsamenamespace:
                          type: boolean
                    serviceaccounts:
                      type: array
                      items:
                        type: string
                    finalizers:
                      type: array
                      items:
                        type: string
              rbac:
                type: object
                properties:
                  admingroup:
                    type: string
                  devgroup:
                    type: string
                  viewergroup:
                    type: string
          status:
            description: Status defines the observed state of Project
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
